/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9FifK9QHyod
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { Skeleton } from '@/components/ui/skeleton';
import { CardContent, Card } from '@/components/ui/card';

export function EventsSkeleton() {
  return (
    <div className='w-full max-w-sm rounded-lg border divide-y'>
      <div className='flex flex-col w-full'>
        <div className='flex flex-col p-3'>
          <div className='flex items-center space-x-2 mb-2'>
            <Skeleton className='w-24 h-3 rounded-lg' />
            <Skeleton className='w-16 h-2 rounded-lg' />
          </div>
          <div className='flex items-center space-x-2 mb-2'>
            <Skeleton className='w-24 h-3 rounded-lg' />
            <Skeleton className='w-16 h-2 rounded-lg' />
          </div>
          <div className='flex items-center space-x-2'>
            <Skeleton className='w-24 h-3 rounded-lg' />
            <Skeleton className='w-16 h-2 rounded-lg' />
          </div>
        </div>
      </div>
    </div>
  );
}
