/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gRYofKj1Q1j
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { CardContent, Card } from "@/components/ui/card"

export function EventCard({}) {
  return (
    <Card className="w-full max-w-sm p-0">
      <CardContent className="p-4">
        <div className="flex items-center gap-4">
          <div className="w-3 h-3 rounded-full bg-gray-200" />
          <div className="grid gap-1">
            <p className="text-sm font-medium leading-none">February 28, 2023</p>
            <p className="text-xs font-medium tracking-wide uppercase">10:00am - 11:00am</p>
          </div>
        </div>
      </CardContent>
      <CardContent className="p-4">
        <h3 className="text-base font-semibold">Design Review</h3>
        <p className="text-sm text-gray-500">Discussing new mockups</p>
      </CardContent>
    </Card>
  )
}
