/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9FifK9QHyod
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { Skeleton } from "@/components/ui/skeleton"
import { CardContent, Card } from "@/components/ui/card"

export function EventsSkeleton() {
  return (
    <Card className="w-full max-w-sm p-0">
      <CardContent className="p-4">
        <div className="flex items-center gap-4">
          <CalendarIcon className="h-6 w-6" />
          <div className="flex flex-col">
            <Skeleton className="w-24 h-3 rounded-lg" />
            <Skeleton className="mt-1 w-16 h-2 rounded-lg" />
          </div>
        </div>
      </CardContent>
    </Card>
  )
}

function CalendarIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}
